- name: find
  find:
    paths: ../patch_storage/
    patterns: "p{{ download_patch.number }}*{{ download_patch.mos_regexp }}*"
  register: info
  delegate_to: localhost

- debug:
    var: info.files.0.path

- name: Download patch {{ .download_patch }} from MOS using getMOSPatch.jar
  ansible.builtin.command: "java -jar ../patch_storage/getMOSPatch.jar patch={{ download_patch.number }}  MOSUser={{ mos_user }} MOSPass={{ mos_pass }} platform={{ download_patch.mos_platform }} regexp=.*{{ download_patch.mos_regexp }}.* download=all"
  #ansible.builtin.command: "pwd"
  register: out1
  delegate_to: localhost
  args:
    chdir: ../patch_storage
  when: info.files.0.path is not defined

- debug: 
    var: out1.stdout_lines

