# current PWD for playbook execution is: ~/playbooks - so 

- name: Creates STAGE directory
  file:
    path: ../{{ local_stage }}/{{ cycle }}
    state: directory 
    mode: 0777
  delegate_to: localhost

- name: Check if patch exists {{ mos_download.number }} locally - will download only if not existing
  ansible.builtin.find:
    paths: ../{{ local_stage }}/{{ cycle }}
    patterns: "p{{ item.number }}*{{ item.mos_regexp }}*"
  register: info
  delegate_to: localhost
  loop: "{{ mos_download | flatten }}"

- debug:
    var: info
    verbosity: 1


- name: Download patch {{ mos_download.number  }} from MOS using getMOSPatch.jar
  #ansible.builtin.command: java -jar ../download/getMOSPatch.jar patch={{ item.number }}  MOSUser={{ mos_user }} MOSPass={{ mos_pass }} platform={{ item.mos_platform }} regexp=.*{{ item.mos_regexp }}.* download=all
  ansible.builtin.command: java -jar ../roles/download/files/getMOSPatch.jar patch={{ item.number }}  platform={{ item.mos_platform }} regexp=.*{{ item.mos_regexp }}.* download=all MOSUser={{ mos_user }} MOSPass={{ mos_pass }} stagedir=../{{ local_stage }}/{{ cycle }}
  #ansible.builtin.command: "pwd"
  register: out1
  delegate_to: localhost
  loop: "{{ mos_download |flatten }}"  
  when: info.files.0.path is not defined

- debug: 
    var: out1.stdout_lines

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: out1
    verbosity: 1