- name: Copy OPatch Script to Server
  template:
    src: "OH_patch_opatch.sh"
    dest: "{{ target_stage_path }}/scripts/{{ oracle_sid }}_{{ apply_opatch.number }}_OH_patch_opatch.sh"
    owner: "{{ target_os_user }}"
    group: "{{ target_os_group }}"
    force: yes
    mode: 0744
  loop: "{{ apply_opatch }}"
  loop_control:
    loop_var: apply_opatch

# using shell module as it's only creating log file with tee (not script, nor command does it)
- name: Apply OPatch to target - {{ oracle_sid }}, oracle_home - {{ oracle_home }}
  #ansible.builtin.command: "sh {{ target_stage_path }}/scripts/{{ oracle_sid }}_{{ apply_opatch.number }}_OH_patch_opatch.sh | tee -a {{ target_stage_path }}/logs/{{ oracle_sid }}_{{ apply_opatch.number }}_OH_patch_opatch.sh.log"
  shell: "{{ target_stage_path }}/scripts/{{ oracle_sid }}_{{ apply_opatch.number }}_OH_patch_opatch.sh | tee -a {{ target_stage_path }}/logs/{{ oracle_sid }}_{{ apply_opatch.number }}_OH_patch_opatch.sh_$(date \"+%Y%m%d_%H%M%S\").log 2>&1"
  register: out1
  loop: "{{ apply_opatch }}"
  loop_control:
    loop_var: apply_opatch

- name: OPatch Version
  ansible.builtin.command: "{{ oracle_home }}/OPatch/opatch version"
  register: out1

- debug: 
    var: out1.stdout_lines