- name: OPatch version
  ansible.builtin.command: "{{ oracle_home }}/OPatch/opatch version"
  #ansible.builtin.command: "{{ oracle_home }}/OPatch/opatch lspatches"
  register: out1

- name: OPatch lspatches
  ansible.builtin.command: "{{ oracle_home }}/OPatch/opatch lspatches"
  register: out2

- name: OPatch lsinv
  ansible.builtin.command: "{{ oracle_home }}/OPatch/opatch lsinventory"
  register: out3

- debug: 
    var: out1.stdout_lines
    
- debug:
    var: out2.stdout_lines
    
- debug:
    var: out3.stdout_lines
    
