- name: Pushing STOP script
  ansible.builtin.template:
    src: stop_rdbms_19c.sh.j2
    dest: "{{ remote_bin }}/{{ env }}_{{target}}_stop_rdbms_19c.sh"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

- name: Execute ORACLE STOP script
  ansible.builtin.shell: 
    sudo su - {{ soft_user }} -c "sh {{ remote_bin }}/{{ env }}_{{target}}_stop_rdbms_19c.sh | tee -a {{ remote_logs }}/{{ env }}_{{target}}_$(date '+%Y%m%d_%H%M%S')_stop_rdbms_19c.sh"
  register: reg_output

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: reg_output.stdout_lines
    verbosity: 0