- name: Check if target stage exists - {{ target_stage_path }} creates if not
  file:
    path: "{{ target_stage_path }}"
    state: directory
    mode: '0755'

- name: Stage Patches from vars/{{ env }}/{{ target }}
  include_tasks: copy.yml
  loop: "{{ stage_patch }}"
  loop_control:
    loop_var: stage_patch

- name: List Target staging area - {{ target_stage_path }} 
  ansible.builtin.command: "ls -lrt {{ target_stage_path }}"
  register: out1
  
- debug: 
    var: out1.stdout_lines