- name: Download Patches from vars/{{ env }}/{{ target }}
  include_tasks: down_local.yml
  loop: "{{ download_patch }}"
  loop_control:
    loop_var: download_patch

- name: List Staging area (local)
  ansible.builtin.command: "ls -lrt"
  #ansible.builtin.command: "pwd"
  register: out1
  delegate_to: localhost
  args:
    chdir: ../patch_storage

- debug: 
    var: out1.stdout_lines